"""JAX-accelerated EvoGym soft robot physics simulator."""

from __future__ import annotations

from jax_evogym.constants import (
    CONTRACTILE,
    EMPTY,
    FIXED,
    H_ACT,
    RIGID,
    SOFT,
    V_ACT,
)
from jax_evogym.world import EvoWorld, WorldObject
from jax_evogym.types import (
    ActuatorInfo,
    BuiltWorld,
    ClimberEnvState,
    CollisionData,
    DeformationInfo,
    EnvState,
    GridData,
    JumperEnvState,
    ObjectTemplate,
    OrientedEnvState,
    PerAxisActuatorInfo,
    PhysicsConstants,
    RenderInfo,
    RenderStepOutput,
    ShapeEnvState,
    SimState,
    StaticColliderData,
    SpringTopology,
    StepOutput,
    WorldTemplate,
    WorldTemplateSet,
    default_physics_constants,
    stiction_physics_constants,
)
from jax_evogym.build import (
    compile_world_template,
    compile_world_templates,
    instantiate_world,
)
from jax_evogym.utils import (
    get_full_connectivity,
    has_actuator,
    is_connected,
    make_sim_state,
    sample_robot,
    voxel_to_dense_mass_spring,
)
from jax_evogym.jax_utils import (
    jax_build_actuator_info,
    jax_build_collision_data,
    jax_build_deformation_info,
    jax_build_per_axis_actuator_info,
    jax_build_sim_state,
    jax_compose_grid,
    precompute_grid,
)
from jax_evogym.physics import compute_forces, rk4_step, symplectic_euler_step
from jax_evogym.constraints import resolve_edge_constraints
from jax_evogym.actuators import (
    set_actuator_goals,
    set_per_axis_goals,
    update_actuators,
)
from jax_evogym.collision import (
    check_triple_capacity,
    is_self_colliding,
    make_collision_data,
    resolve_collisions,
    resolve_collisions_dynamic_broadphase,
    resolve_collisions_static_indexed,
    resolve_static_collisions,
)
from jax_evogym.deformation import compute_deformation
from jax_evogym.sim import env_step, make_episode_step, physics_substep
from jax_evogym.render import (
    RenderConfig,
    make_render_episode_step,
    render_episode,
    render_frame,
    render_top_k,
    rerun_top_k,
    save_gif,
)
from jax_evogym.environment import WalkerV0, make_walker_episode_step
from jax_evogym.environments import (
    BridgeWalkerV0,
    ClimberV0,
    HeightMaximizerV0,
    JumperV0,
    UpStepperV0,
    WingspanMaximizerV0,
    make_bridge_walker_episode_step,
    make_climber_episode_step,
    make_jumper_episode_step,
    make_shape_episode_step,
    make_upstepper_episode_step,
)

__all__ = [
    "CONTRACTILE",
    "EMPTY",
    "FIXED",
    "H_ACT",
    "RIGID",
    "SOFT",
    "V_ACT",
    "EvoWorld",
    "WorldObject",
    "ActuatorInfo",
    "BuiltWorld",
    "ClimberEnvState",
    "CollisionData",
    "DeformationInfo",
    "EnvState",
    "GridData",
    "JumperEnvState",
    "ObjectTemplate",
    "OrientedEnvState",
    "PerAxisActuatorInfo",
    "PhysicsConstants",
    "RenderInfo",
    "RenderStepOutput",
    "ShapeEnvState",
    "SimState",
    "StaticColliderData",
    "SpringTopology",
    "StepOutput",
    "WorldTemplate",
    "WorldTemplateSet",
    "default_physics_constants",
    "stiction_physics_constants",
    "compile_world_template",
    "compile_world_templates",
    "instantiate_world",
    "get_full_connectivity",
    "has_actuator",
    "is_connected",
    "make_sim_state",
    "sample_robot",
    "voxel_to_dense_mass_spring",
    "jax_build_actuator_info",
    "jax_build_collision_data",
    "jax_build_deformation_info",
    "jax_build_per_axis_actuator_info",
    "jax_build_sim_state",
    "jax_compose_grid",
    "precompute_grid",
    "compute_forces",
    "rk4_step",
    "symplectic_euler_step",
    "resolve_edge_constraints",
    "set_actuator_goals",
    "set_per_axis_goals",
    "update_actuators",
    "check_triple_capacity",
    "is_self_colliding",
    "make_collision_data",
    "resolve_collisions",
    "resolve_collisions_dynamic_broadphase",
    "resolve_collisions_static_indexed",
    "resolve_static_collisions",
    "compute_deformation",
    "env_step",
    "make_episode_step",
    "physics_substep",
    "RenderConfig",
    "make_render_episode_step",
    "render_episode",
    "render_frame",
    "render_top_k",
    "rerun_top_k",
    "save_gif",
    "WalkerV0",
    "make_walker_episode_step",
    "BridgeWalkerV0",
    "ClimberV0",
    "HeightMaximizerV0",
    "JumperV0",
    "UpStepperV0",
    "WingspanMaximizerV0",
    "make_bridge_walker_episode_step",
    "make_climber_episode_step",
    "make_jumper_episode_step",
    "make_shape_episode_step",
    "make_upstepper_episode_step",
]
