"""Physics constants and voxel type definitions.

The stable square-cell constants follow EvoGym's C++ defaults unless a nearby
comment marks an intentional JAX-side extension or correction. Spring constants
are material properties and are not scaled by ``CELL_SIZE``.
"""

# --- Voxel types (ObjectCreator.h / Boxel.h) ---
EMPTY = 0
RIGID = 1
SOFT = 2
H_ACT = 3   # Horizontal actuator
V_ACT = 4   # Vertical actuator
FIXED = 5   # Anchored (immovable)
CONTRACTILE = 6  # Universal actuator: per-axis control at runtime
SLOPE_UP_RIGHT = 7
SLOPE_UP_LEFT = 8
SLOPE_DOWN_RIGHT = 9
SLOPE_DOWN_LEFT = 10
SLOPE2_UP_RIGHT_LIGHT = 11
SLOPE2_UP_RIGHT_HEAVY = 12
SLOPE2_UP_LEFT_HEAVY = 13
SLOPE2_UP_LEFT_LIGHT = 14
SLOPE2_DOWN_RIGHT_LIGHT = 15
SLOPE2_DOWN_RIGHT_HEAVY = 16
SLOPE2_DOWN_LEFT_HEAVY = 17
SLOPE2_DOWN_LEFT_LIGHT = 18
SLOPE3_UP_RIGHT_LIGHT = 19
SLOPE3_UP_RIGHT_MID = 20
SLOPE3_UP_RIGHT_HEAVY = 21
SLOPE3_UP_LEFT_HEAVY = 22
SLOPE3_UP_LEFT_MID = 23
SLOPE3_UP_LEFT_LIGHT = 24
SLOPE3_DOWN_RIGHT_HEAVY = 25
SLOPE3_DOWN_RIGHT_MID = 26
SLOPE3_DOWN_RIGHT_LIGHT = 27
SLOPE3_DOWN_LEFT_LIGHT = 28
SLOPE3_DOWN_LEFT_MID = 29
SLOPE3_DOWN_LEFT_HEAVY = 30

ACTUATOR_TYPES = {H_ACT, V_ACT, CONTRACTILE}
SLOPE_1X1_TYPES = {
    SLOPE_UP_RIGHT,
    SLOPE_UP_LEFT,
    SLOPE_DOWN_RIGHT,
    SLOPE_DOWN_LEFT,
}
SLOPE_2X1_TYPES = {
    SLOPE2_UP_RIGHT_LIGHT,
    SLOPE2_UP_RIGHT_HEAVY,
    SLOPE2_UP_LEFT_HEAVY,
    SLOPE2_UP_LEFT_LIGHT,
    SLOPE2_DOWN_RIGHT_LIGHT,
    SLOPE2_DOWN_RIGHT_HEAVY,
    SLOPE2_DOWN_LEFT_HEAVY,
    SLOPE2_DOWN_LEFT_LIGHT,
}
SLOPE_2X1_HEAVY_TYPES = {
    SLOPE2_UP_RIGHT_HEAVY,
    SLOPE2_UP_LEFT_HEAVY,
    SLOPE2_DOWN_RIGHT_HEAVY,
    SLOPE2_DOWN_LEFT_HEAVY,
}
SLOPE_2X1_LIGHT_TYPES = {
    SLOPE2_UP_RIGHT_LIGHT,
    SLOPE2_UP_LEFT_LIGHT,
    SLOPE2_DOWN_RIGHT_LIGHT,
    SLOPE2_DOWN_LEFT_LIGHT,
}
SLOPE_3X1_TYPES = {
    SLOPE3_UP_RIGHT_LIGHT,
    SLOPE3_UP_RIGHT_MID,
    SLOPE3_UP_RIGHT_HEAVY,
    SLOPE3_UP_LEFT_HEAVY,
    SLOPE3_UP_LEFT_MID,
    SLOPE3_UP_LEFT_LIGHT,
    SLOPE3_DOWN_RIGHT_HEAVY,
    SLOPE3_DOWN_RIGHT_MID,
    SLOPE3_DOWN_RIGHT_LIGHT,
    SLOPE3_DOWN_LEFT_LIGHT,
    SLOPE3_DOWN_LEFT_MID,
    SLOPE3_DOWN_LEFT_HEAVY,
}
SLOPE_3X1_HEAVY_TYPES = {
    SLOPE3_UP_RIGHT_HEAVY,
    SLOPE3_UP_LEFT_HEAVY,
    SLOPE3_DOWN_RIGHT_HEAVY,
    SLOPE3_DOWN_LEFT_HEAVY,
}
SLOPE_3X1_MID_TYPES = {
    SLOPE3_UP_RIGHT_MID,
    SLOPE3_UP_LEFT_MID,
    SLOPE3_DOWN_RIGHT_MID,
    SLOPE3_DOWN_LEFT_MID,
}
SLOPE_3X1_LIGHT_TYPES = {
    SLOPE3_UP_RIGHT_LIGHT,
    SLOPE3_UP_LEFT_LIGHT,
    SLOPE3_DOWN_RIGHT_LIGHT,
    SLOPE3_DOWN_LEFT_LIGHT,
}
SLOPE_TYPES = {
    *SLOPE_1X1_TYPES,
    *SLOPE_2X1_TYPES,
    *SLOPE_3X1_TYPES,
}
DYNAMIC_VOXEL_TYPES = {RIGID, SOFT, H_ACT, V_ACT, CONTRACTILE}
STABLE_STATIC_TERRAIN_TYPES = {FIXED}
STABLE_WORLD_CELL_TYPES = {EMPTY, FIXED, *DYNAMIC_VOXEL_TYPES}
EXPERIMENTAL_STATIC_TERRAIN_TYPES = {FIXED, *SLOPE_TYPES}
STATIC_TERRAIN_TYPES = EXPERIMENTAL_STATIC_TERRAIN_TYPES  # compatibility alias
WORLD_CELL_TYPES = {EMPTY, FIXED, *DYNAMIC_VOXEL_TYPES, *SLOPE_TYPES}

SLOPE_2X1_MATE_TYPE = {
    SLOPE2_UP_RIGHT_LIGHT: SLOPE2_UP_RIGHT_HEAVY,
    SLOPE2_UP_RIGHT_HEAVY: SLOPE2_UP_RIGHT_LIGHT,
    SLOPE2_UP_LEFT_HEAVY: SLOPE2_UP_LEFT_LIGHT,
    SLOPE2_UP_LEFT_LIGHT: SLOPE2_UP_LEFT_HEAVY,
    SLOPE2_DOWN_RIGHT_LIGHT: SLOPE2_DOWN_RIGHT_HEAVY,
    SLOPE2_DOWN_RIGHT_HEAVY: SLOPE2_DOWN_RIGHT_LIGHT,
    SLOPE2_DOWN_LEFT_HEAVY: SLOPE2_DOWN_LEFT_LIGHT,
    SLOPE2_DOWN_LEFT_LIGHT: SLOPE2_DOWN_LEFT_HEAVY,
}
SLOPE_2X1_MATE_OFFSET = {
    SLOPE2_UP_RIGHT_LIGHT: (1, 0),
    SLOPE2_UP_RIGHT_HEAVY: (-1, 0),
    SLOPE2_UP_LEFT_HEAVY: (1, 0),
    SLOPE2_UP_LEFT_LIGHT: (-1, 0),
    SLOPE2_DOWN_RIGHT_LIGHT: (-1, 0),
    SLOPE2_DOWN_RIGHT_HEAVY: (1, 0),
    SLOPE2_DOWN_LEFT_HEAVY: (-1, 0),
    SLOPE2_DOWN_LEFT_LIGHT: (1, 0),
}
SLOPE_3X1_NEIGHBOR_RULES = {
    SLOPE3_UP_RIGHT_LIGHT: ((1, 0, SLOPE3_UP_RIGHT_MID), (2, 0, SLOPE3_UP_RIGHT_HEAVY)),
    SLOPE3_UP_RIGHT_MID: ((-1, 0, SLOPE3_UP_RIGHT_LIGHT), (1, 0, SLOPE3_UP_RIGHT_HEAVY)),
    SLOPE3_UP_RIGHT_HEAVY: ((-1, 0, SLOPE3_UP_RIGHT_MID), (-2, 0, SLOPE3_UP_RIGHT_LIGHT)),
    SLOPE3_UP_LEFT_HEAVY: ((1, 0, SLOPE3_UP_LEFT_MID), (2, 0, SLOPE3_UP_LEFT_LIGHT)),
    SLOPE3_UP_LEFT_MID: ((-1, 0, SLOPE3_UP_LEFT_HEAVY), (1, 0, SLOPE3_UP_LEFT_LIGHT)),
    SLOPE3_UP_LEFT_LIGHT: ((-1, 0, SLOPE3_UP_LEFT_MID), (-2, 0, SLOPE3_UP_LEFT_HEAVY)),
    SLOPE3_DOWN_RIGHT_HEAVY: ((1, 0, SLOPE3_DOWN_RIGHT_MID), (2, 0, SLOPE3_DOWN_RIGHT_LIGHT)),
    SLOPE3_DOWN_RIGHT_MID: ((-1, 0, SLOPE3_DOWN_RIGHT_HEAVY), (1, 0, SLOPE3_DOWN_RIGHT_LIGHT)),
    SLOPE3_DOWN_RIGHT_LIGHT: ((-1, 0, SLOPE3_DOWN_RIGHT_MID), (-2, 0, SLOPE3_DOWN_RIGHT_HEAVY)),
    SLOPE3_DOWN_LEFT_LIGHT: ((1, 0, SLOPE3_DOWN_LEFT_MID), (2, 0, SLOPE3_DOWN_LEFT_HEAVY)),
    SLOPE3_DOWN_LEFT_MID: ((-1, 0, SLOPE3_DOWN_LEFT_LIGHT), (1, 0, SLOPE3_DOWN_LEFT_HEAVY)),
    SLOPE3_DOWN_LEFT_HEAVY: ((-1, 0, SLOPE3_DOWN_LEFT_MID), (-2, 0, SLOPE3_DOWN_LEFT_LIGHT)),
}

SLOPE_MIRROR_X_MAP = {
    SLOPE_UP_RIGHT: SLOPE_UP_LEFT,
    SLOPE_UP_LEFT: SLOPE_UP_RIGHT,
    SLOPE_DOWN_RIGHT: SLOPE_DOWN_LEFT,
    SLOPE_DOWN_LEFT: SLOPE_DOWN_RIGHT,
    SLOPE2_UP_RIGHT_LIGHT: SLOPE2_UP_LEFT_LIGHT,
    SLOPE2_UP_RIGHT_HEAVY: SLOPE2_UP_LEFT_HEAVY,
    SLOPE2_UP_LEFT_HEAVY: SLOPE2_UP_RIGHT_HEAVY,
    SLOPE2_UP_LEFT_LIGHT: SLOPE2_UP_RIGHT_LIGHT,
    SLOPE2_DOWN_RIGHT_LIGHT: SLOPE2_DOWN_LEFT_LIGHT,
    SLOPE2_DOWN_RIGHT_HEAVY: SLOPE2_DOWN_LEFT_HEAVY,
    SLOPE2_DOWN_LEFT_HEAVY: SLOPE2_DOWN_RIGHT_HEAVY,
    SLOPE2_DOWN_LEFT_LIGHT: SLOPE2_DOWN_RIGHT_LIGHT,
    SLOPE3_UP_RIGHT_LIGHT: SLOPE3_UP_LEFT_LIGHT,
    SLOPE3_UP_RIGHT_MID: SLOPE3_UP_LEFT_MID,
    SLOPE3_UP_RIGHT_HEAVY: SLOPE3_UP_LEFT_HEAVY,
    SLOPE3_UP_LEFT_HEAVY: SLOPE3_UP_RIGHT_HEAVY,
    SLOPE3_UP_LEFT_MID: SLOPE3_UP_RIGHT_MID,
    SLOPE3_UP_LEFT_LIGHT: SLOPE3_UP_RIGHT_LIGHT,
    SLOPE3_DOWN_RIGHT_HEAVY: SLOPE3_DOWN_LEFT_HEAVY,
    SLOPE3_DOWN_RIGHT_MID: SLOPE3_DOWN_LEFT_MID,
    SLOPE3_DOWN_RIGHT_LIGHT: SLOPE3_DOWN_LEFT_LIGHT,
    SLOPE3_DOWN_LEFT_LIGHT: SLOPE3_DOWN_RIGHT_LIGHT,
    SLOPE3_DOWN_LEFT_MID: SLOPE3_DOWN_RIGHT_MID,
    SLOPE3_DOWN_LEFT_HEAVY: SLOPE3_DOWN_RIGHT_HEAVY,
}

SLOPE_ROTATE_CW_MAP = {
    SLOPE_UP_RIGHT: SLOPE_UP_LEFT,
    SLOPE_UP_LEFT: SLOPE_DOWN_RIGHT,
    SLOPE_DOWN_RIGHT: SLOPE_DOWN_LEFT,
    SLOPE_DOWN_LEFT: SLOPE_UP_RIGHT,
    # 2x1 ramps intentionally do not support 90-degree rotation in this release.
    SLOPE2_UP_RIGHT_LIGHT: SLOPE2_UP_RIGHT_LIGHT,
    SLOPE2_UP_RIGHT_HEAVY: SLOPE2_UP_RIGHT_HEAVY,
    SLOPE2_UP_LEFT_HEAVY: SLOPE2_UP_LEFT_HEAVY,
    SLOPE2_UP_LEFT_LIGHT: SLOPE2_UP_LEFT_LIGHT,
    SLOPE2_DOWN_RIGHT_LIGHT: SLOPE2_DOWN_RIGHT_LIGHT,
    SLOPE2_DOWN_RIGHT_HEAVY: SLOPE2_DOWN_RIGHT_HEAVY,
    SLOPE2_DOWN_LEFT_HEAVY: SLOPE2_DOWN_LEFT_HEAVY,
    SLOPE2_DOWN_LEFT_LIGHT: SLOPE2_DOWN_LEFT_LIGHT,
    # 3x1 ramps intentionally do not support 90-degree rotation in this release.
    SLOPE3_UP_RIGHT_LIGHT: SLOPE3_UP_RIGHT_LIGHT,
    SLOPE3_UP_RIGHT_MID: SLOPE3_UP_RIGHT_MID,
    SLOPE3_UP_RIGHT_HEAVY: SLOPE3_UP_RIGHT_HEAVY,
    SLOPE3_UP_LEFT_HEAVY: SLOPE3_UP_LEFT_HEAVY,
    SLOPE3_UP_LEFT_MID: SLOPE3_UP_LEFT_MID,
    SLOPE3_UP_LEFT_LIGHT: SLOPE3_UP_LEFT_LIGHT,
    SLOPE3_DOWN_RIGHT_HEAVY: SLOPE3_DOWN_RIGHT_HEAVY,
    SLOPE3_DOWN_RIGHT_MID: SLOPE3_DOWN_RIGHT_MID,
    SLOPE3_DOWN_RIGHT_LIGHT: SLOPE3_DOWN_RIGHT_LIGHT,
    SLOPE3_DOWN_LEFT_LIGHT: SLOPE3_DOWN_LEFT_LIGHT,
    SLOPE3_DOWN_LEFT_MID: SLOPE3_DOWN_LEFT_MID,
    SLOPE3_DOWN_LEFT_HEAVY: SLOPE3_DOWN_LEFT_HEAVY,
}

# --- Spring constants (ObjectCreator.h:40-47) ---
# Raw C++ values — NOT scaled by cell_size
RIGID_MAIN_K = 300_000_000.0 / 3.5       # ~85,714,286
ACTUATOR_MAIN_K = 300_000_000.0 / 5.0    # 60,000,000
SOFT_MAIN_K = 300_000_000.0 / 6.0        # 50,000,000

RIGID_DIAG_K = RIGID_MAIN_K / 2.0        # ~42,857,143
ACTUATOR_DIAG_K = ACTUATOR_MAIN_K / 2.0  # 30,000,000
SOFT_DIAG_K = SOFT_MAIN_K / 4.0          # 12,500,000

# Map: voxel_type -> (main_k, diag_k)
SPRING_CONSTANTS = {
    RIGID: (RIGID_MAIN_K, RIGID_DIAG_K),
    SOFT:  (SOFT_MAIN_K, SOFT_DIAG_K),
    H_ACT: (ACTUATOR_MAIN_K, ACTUATOR_DIAG_K),
    V_ACT: (ACTUATOR_MAIN_K, ACTUATOR_DIAG_K),
    CONTRACTILE: (ACTUATOR_MAIN_K, ACTUATOR_DIAG_K),
    FIXED: (RIGID_MAIN_K, RIGID_DIAG_K),
}

# --- Physics constants (PhysicsEngine.h:16-27) ---
# Damping scaling rules:
#   critical_damping = 2 * sqrt(stiffness * point_mass)
#   damping_ratio (ζ) = damping / critical_damping
#   COR ≈ exp(-ζ * π / sqrt(1 - ζ²))
#
# Target: ζ ≈ 0.7 (COR ≈ 0.05) — appropriate for gel/tissue soft bodies
# (Keijzer contractile epithelia, Trichoplax/Hydra tissue mechanics).
# Reference: MuJoCo defaults to ζ=1.0, VoxCraft to max damping, Bullet to COR=0.
#
# Object-terrain (k=2,100,000, m_eff=m=1, infinite-mass wall):
#   critical = 2 * sqrt(2,100,000) ≈ 2,898
#   ζ=0.7 → damping = 0.7 * 2,898 ≈ 2,030
#
# Ground plane (k=14,000,000, m_eff=m=1):
#   critical = 2 * sqrt(14,000,000) ≈ 7,483
#   ζ=0.7 → damping = 0.7 * 7,483 ≈ 5,238
DT = 0.0001
GRAVITY = 110.0                           # NOT 1100 (MLX bug)
VISCOUS_DRAG = 0.1                        # NOT 1.0 (MLX bug)
COLLISION_CONST_GROUND = 2_000_000.0 * 7  # 14,000,000
COLLISION_CONST_OBJ = 300_000.0 * 7       # 2,100,000
COLLISION_VEL_DAMPING = 2_030.0           # was 140.0 (C++ PhysicsEngine.h:22)
GROUND_VEL_DAMPING = 5_238.0             # C++ has no ground normal damping
COLLISION_BASE_DIST = 0.005
STATIC_FRICTION_CONST = 0.5
DYNAMIC_FRICTION_CONST = 0.2
FRICTION_CONST = 150.0 * 8               # 1200 (obj-obj only)
GROUND_FRICTION_CONST = 10               # Hardcoded in PhysicsEngine.cpp:577
TERRAIN_STICTION_STIFFNESS = 20_000.0
GROUND_STICTION_STIFFNESS = 20_000.0
TERRAIN_STICTION_SWITCH_SPEED = 0.12
GROUND_STICTION_SWITCH_SPEED = 0.12
STICTION_SCOPE_FLOOR_SLOPE_ONLY = 0
STICTION_SCOPE_ALL_STATIC = 1
STICTION_SCOPE_SLOPE_ONLY = 2
FRICTION_MODEL_NONE = 0
FRICTION_MODEL_PROJECTED_ANCHOR = 1
FRICTION_MODEL_PROJECTED_DEFORMATION = 2
ANCHOR_STIFFNESS = 50_000.0
DEFORMATION_STIFFNESS = 50_000.0
DEFORMATION_DAMPING = 500.0
DEFORMATION_DECAY = 0.95
DEFORMATION_NORMAL_BLEED = 0.98
BREAKAWAY_THRESHOLD = 0.0
FRICTION_CONSTRAINT_MODE_OFF = 0
FRICTION_CONSTRAINT_MODE_TERRAIN_PBD_ANCHOR = 1
FRICTION_ANCHOR_STIFFNESS = 50_000.0
FRICTION_ANCHOR_CORRECTION = 1.0
FRICTION_ANCHOR_PERSIST_SUBSTEPS = 10
SLOPE_CONTACT_MODE_NONE = 0
SLOPE_CONTACT_MODE_GAP_SUPPORT = 1
SLOPE_CONTACT_MODE_LEGACY_GAP_SUPPORT = SLOPE_CONTACT_MODE_GAP_SUPPORT  # compatibility alias
SLOPE_CONTACT_MODE_CONTINUITY_ASSIST = 2
SLOPE_CONTACT_MODE_GRAVITY_PRELOAD_EXPERIMENTAL = 3
SLOPE_CONTACT_MODE = SLOPE_CONTACT_MODE_NONE
SLOPE_CONTACT_NEAR_DIST = 0.01
SLOPE_CONTACT_RELEASE_SPEED = 0.05
SLOPE_CONTACT_NORMAL_DAMPING = 10.0
SLOPE_CONTACT_TANGENT_DAMPING = 10.0
SLOPE_CONTACT_ASSIST_MU = 0.5
SLOPE_GRIP_ENABLED = False
SLOPE_GRIP_STATIC_FRICTION_CONST = 0.5
SLOPE_GRIP_SUPPORT_STIFFNESS = 20_000.0
SLOPE_GRIP_SWITCH_SPEED = 0.12
SLOPE_GRIP_NEAR_CONTACT_DIST = 0.08
SLOPE_GRIP_NEAR_RELEASE_SPEED = 0.25
SLOPE_GRIP_SCOPE = STICTION_SCOPE_FLOOR_SLOPE_ONLY
# Slope contact/grip constants are retained for compatibility with older
# experiments and configs. The stable library treats experimental slope terrain
# as geometry-only: sloped edges receive normal contact response, but these
# tangential support/friction controls are no-ops.
MANIFOLD_NORMAL_COS_THRESHOLD = 0.95  # ~18 degrees tolerance for same-surface matching

# --- Simulation structure (Sim.cpp:23) ---
PHYSICS_UPDATES_PER_STEP = 30

# --- Grid constants (ObjectCreator.h:36-38) ---
CELL_SIZE = 0.1
POINT_MASS = 1.0

# --- Actuator constants (PhysicsEngine.cpp:101-102) ---
ACTUATOR_CONVERGENCE = 0.006

# --- Integrator constants ---
INTEGRATOR_RK4 = 0
INTEGRATOR_SYMPLECTIC_EULER = 1
INTEGRATOR_NAME_TO_CODE = {
    "rk4": INTEGRATOR_RK4,
    "symplectic_euler": INTEGRATOR_SYMPLECTIC_EULER,
}
INTEGRATOR_CODE_TO_NAME = {
    INTEGRATOR_RK4: "rk4",
    INTEGRATOR_SYMPLECTIC_EULER: "symplectic_euler",
}

# --- Dense grid defaults ---
DEFAULT_GRID_H = 14
DEFAULT_GRID_W = 14

# --- Indexed collision caps ---
# Fixed-size buffers for indexed collision triples.
# Sized for 10x40 sparse grids with ~170 active boxels.
MAX_TRIPLES = 131_072
MAX_SELF_TRIPLES = 16_384
